# Testing 2 input and 1 output Linear Regression

In [5]:
import numpy as np
import pandas as pd
data=pd.read_csv("data.csv")
data.columns=["input1","input2"]
data["output"]=(2*data["input1"]+3*data["input2"])/5 #randomly adding the third column and woh output treat
print(data)

       input1     input2     output
0   53.426804  68.777596  62.637279
1   61.530358  62.562382  62.149573
2   47.475640  71.546632  61.918235
3   59.813208  87.230925  76.263838
4   55.142188  78.211518  68.983786
..        ...        ...        ...
94  50.030174  81.536991  68.934264
95  49.239765  72.111832  62.963006
96  50.039576  85.232007  71.155035
97  48.149859  66.224958  58.994918
98  25.128485  53.454394  42.124030

[99 rows x 3 columns]


Now convert this to numpy 2D array as processing is easier waha

In [6]:
data=np.array(data)
print(data)

[[ 53.42680403  68.77759598  62.6372792 ]
 [ 61.53035803  62.5623823   62.14957259]
 [ 47.47563963  71.54663223  61.91823519]
 [ 59.81320787  87.23092513  76.26383823]
 [ 55.14218841  78.21151827  68.98378633]
 [ 52.21179669  79.64197305  68.66990251]
 [ 39.29956669  59.17148932  51.22272027]
 [ 48.10504169  75.3312423   64.44076205]
 [ 52.55001444  71.30087989  63.80053371]
 [ 45.41973014  55.16567715  51.26729835]
 [ 54.35163488  82.47884676  71.22796201]
 [ 44.1640495   62.00892325  54.87097375]
 [ 58.16847072  75.39287043  68.50311054]
 [ 56.72720806  81.43619216  71.55259852]
 [ 48.95588857  60.72360244  56.01651689]
 [ 44.68719623  82.89250373  67.61038073]
 [ 60.29732685  97.37989686  82.54686886]
 [ 45.61864377  48.84715332  47.5557495 ]
 [ 38.81681754  56.87721319  49.65305493]
 [ 66.18981661  83.87856466  76.80306544]
 [ 65.41605175 118.5912173   97.32115108]
 [ 47.48120861  57.25181946  53.34357512]
 [ 41.57564262  51.39174408  47.46530349]
 [ 51.84518691  75.38065167  65.96

In [7]:
input=data[:,0:2] #input mei all rows/datapoints ke 1st 2 columns
output=data[:,2] #output mei last column
print(input)
print(output)

[[ 53.42680403  68.77759598]
 [ 61.53035803  62.5623823 ]
 [ 47.47563963  71.54663223]
 [ 59.81320787  87.23092513]
 [ 55.14218841  78.21151827]
 [ 52.21179669  79.64197305]
 [ 39.29956669  59.17148932]
 [ 48.10504169  75.3312423 ]
 [ 52.55001444  71.30087989]
 [ 45.41973014  55.16567715]
 [ 54.35163488  82.47884676]
 [ 44.1640495   62.00892325]
 [ 58.16847072  75.39287043]
 [ 56.72720806  81.43619216]
 [ 48.95588857  60.72360244]
 [ 44.68719623  82.89250373]
 [ 60.29732685  97.37989686]
 [ 45.61864377  48.84715332]
 [ 38.81681754  56.87721319]
 [ 66.18981661  83.87856466]
 [ 65.41605175 118.5912173 ]
 [ 47.48120861  57.25181946]
 [ 41.57564262  51.39174408]
 [ 51.84518691  75.38065167]
 [ 59.37082201  74.76556403]
 [ 57.31000344  95.45505292]
 [ 63.61556125  95.22936602]
 [ 46.73761941  79.05240617]
 [ 50.55676015  83.43207142]
 [ 52.22399609  63.35879032]
 [ 35.56783005  41.4128853 ]
 [ 42.43647694  76.61734128]
 [ 58.16454011  96.76956643]
 [ 57.50444762  74.08413012]
 [ 45.44053073

Splitting data into training and testing

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(input,output,random_state=1)

Now, inbuilt Linear Regression use karenge

In [9]:
from sklearn.linear_model import LinearRegression
algorithm=LinearRegression()
algorithm.fit(x_train,y_train)
print("m1 : ",algorithm.coef_[0])
print("m2 : ",algorithm.coef_[1])
print("m3 : ",algorithm.intercept_)

m1 :  0.4000000000000004
m2 :  0.6
m3 :  -2.1316282072803006e-14


Clearly our output was 2/5*x1+3/5*x2+0 joh woh predict baas itne datas se joh really impressive
issi ko kehte output has linear relation wrt x1 and x2 so linear regression se solved

In [10]:
print("Score : ",algorithm.score(x_test,y_test))

Score :  1.0


So score 1 aaya as exact match kar rhe testing output se y_predicted joh ki sahi as m1 and m2 exact hi nikal liya

In [17]:
def get_optimal_coefficient(x_train,y_train):
    '''
    Returns coef_ array [m1,m2,m3]
    Refer copy for mapping
    '''
    x1=x_train[:,0]
    x2=x_train[:,1]
    y=y_train
    a=(x1*x2).mean()
    b=(x1**2).mean()
    c=(x2**2).mean()
    d=x1.mean()
    e=x2.mean()
    f=(x1*y).mean()
    g=(x2*y).mean()
    h=y.mean()
    m2=((d*h-f)*(d*e-a)-(d**2-b)*(e*h-g))/((c-e**2)*(d**2-b)+(d*e-a)**2)
    m1=(e*h-g-(e**2-c)*m2)/(e*d-a)
    m3=h-d*m1-e*m2
    return (m1,m2,m3)

In [18]:
m1,m2,m3=get_optimal_coefficient(x_train,y_train)
print("m1 : ",m1)
print("m2 : ",m2)
print("m3 : ",m3)

m1 :  0.39999999999999364
m2 :  0.6000000000000006
m3 :  2.6290081223123707e-13


Shows that our calculation is perfect!!!!!!!!!!!!!

In [20]:
def coefficient_of_determination(y_predicted,y_actual):
    u=((y_actual-y_predicted)**2).sum()
    v=((y_actual-y_actual.mean())**2).sum()
    return 1-u/v

In [21]:
y_predicted=m1*x_test[:,0]+m2*x_test[:,1]+m3
print("Score : ",coefficient_of_determination(y_predicted,y_test))

Score :  1.0
